global:
  env: production
  ingressclass: production
appName: integration
namespace: production

minReplicas: 1
maxReplicas: 10

serviceport: 80
targetport: 8084

hosts: "*.zetapp.in"
dnsname: integration.zetapp.in

subnet: subnet-06a741cebaf0f7819,subnet-06e90286ced3c92b3,subnet-026043a113ecb3b3a
LBname: production-eks-lbingress

image:
  name: 887417737466.dkr.ecr.ap-south-1.amazonaws.com/integration-prod
  tag: latest
