  #This is QA Config file
  ACTIVE_PROFILE: dev
  SECRETMANAGER_CONFIG: "aws-secretsmanager:/develop/boilerplate"
  AWS_REGION: ap-south-1
  _JAVA_OPTIONS: -javaagent:/var/newrelic.jar -Dnewrelic.config.app_name=integration-develop-eks -Dnewrelic.config.license_key=68091cd17960f5b4a1ea1ca600708bc38876NRAL -Xms256m
